// for (let i = 1; i <= 10; i++) {
//   console.log(i);
// }

// // ต้องการ กรหยสฟั 100 90 80 70 ... 0

// for (let i = 100; i <= 100 && i >= 0; i -= 10) {
//   console.log(i);
// }

// // const animals = ["tiger", "Bear", "Elephant", "Bull"];
// // first index = 0
// // last index = 3
// // length = 4

// for (let i = 0; i < animals.length; i++) {
//   console.log(i, animals[i]);
// }

// const animals = [
//   "Aardvark",
//   "Albatross",
//   "Alligator",
//   "Alpaca",
//   "Ant",
//   "Anteater",
//   "Antelope",
//   "Ape",
//   "Armadillo",
//   "Donkey",
//   "Baboon",
//   "Badger",
//   "Barracuda",
//   "Bat",
//   "Bear",
//   "Beaver",
//   "Bee",
//   "Bison",
//   "Boar",
//   "Buffalo",
//   "Butterfly",
//   "Camel",
//   "Capybara",
//   "Caribou",
//   "Cassowary",
//   "Cat",
//   "Caterpillar",
//   "Cattle",
//   "Chamois",
//   "Cheetah",
//   "Chicken",
//   "Chimpanzee",
//   "Chinchilla",
//   "Chough",
//   "Clam",
//   "Cobra",
//   "Cockroach",
//   "Cod",
//   "Cormorant",
//   "Coyote",
//   "Crab",
//   "Crane",
//   "Crocodile",
//   "Crow",
//   "Curlew",
//   "Deer",
//   "Dinosaur",
//   "Dog",
//   "Dogfish",
//   "Dolphin",
//   "Dotterel",
//   "Dove",
//   "Dragonfly",
//   "Duck",
//   "Dugong",
//   "Dunlin",
//   "Eagle",
//   "Echidna",
//   "Eel",
//   "Eland",
//   "Elephant",
//   "Elk",
//   "Emu",
//   "Falcon",
//   "Ferret",
//   "Finch",
//   "Fish",
//   "Flamingo",
//   "Fly",
//   "Fox",
//   "Frog",
//   "Gaur",
//   "Gazelle",
//   "Gerbil",
//   "Giraffe",
//   "Gnat",
//   "Gnu",
//   "Goat",
//   "Goldfinch",
//   "Goldfish",
//   "Goose",
//   "Gorilla",
//   "Goshawk",
//   "Grasshopper",
//   "Grouse",
//   "Guanaco",
//   "Gull",
//   "Hamster",
//   "Hare",
//   "Hawk",
//   "Hedgehog",
//   "Heron",
//   "Herring",
//   "Hippopotamus",
//   "Hornet",
//   "Horse",
//   "Human",
//   "Hummingbird",
//   "Hyena",
//   "Ibex",
//   "Ibis",
//   "Jackal",
//   "Jaguar",
//   "Jay",
//   "Jellyfish",
//   "Kangaroo",
//   "Kingfisher",
//   "Koala",
//   "Kookabura",
//   "Kouprey",
//   "Kudu",
//   "Lapwing",
//   "Lark",
//   "Lemur",
//   "Leopard",
//   "Lion",
//   "Llama",
//   "Lobster",
//   "Locust",
//   "Loris",
//   "Louse",
//   "Lyrebird",
//   "Magpie",
//   "Mallard",
//   "Manatee",
//   "Mandrill",
//   "Mantis",
//   "Marten",
//   "Meerkat",
//   "Mink",
//   "Mole",
//   "Mongoose",
//   "Monkey",
//   "Moose",
//   "Mosquito",
//   "Mouse",
//   "Mule",
//   "Narwhal",
//   "Newt",
//   "Nightingale",
//   "Octopus",
//   "Okapi",
//   "Opossum",
//   "Oryx",
//   "Ostrich",
//   "Otter",
//   "Owl",
//   "Oyster",
//   "Panther",
//   "Parrot",
//   "Partridge",
//   "Peafowl",
//   "Pelican",
//   "Penguin",
//   "Pheasant",
//   "Pig",
//   "Pigeon",
//   "Pony",
//   "Porcupine",
//   "Porpoise",
//   "Quail",
//   "Quelea",
//   "Quetzal",
//   "Rabbit",
//   "Raccoon",
//   "Rail",
//   "Ram",
//   "Rat",
//   "Raven",
//   "Red deer",
//   "Red panda",
//   "Reindeer",
//   "Rhinoceros",
//   "Rook",
//   "Salamander",
//   "Salmon",
//   "Sand Dollar",
//   "Sandpiper",
//   "Sardine",
//   "Scorpion",
//   "Seahorse",
//   "Seal",
//   "Shark",
//   "Sheep",
//   "Shrew",
//   "Skunk",
//   "Snail",
//   "Snake",
//   "Sparrow",
//   "Spider",
//   "Spoonbill",
//   "Squid",
//   "Squirrel",
//   "Starling",
//   "Stingray",
//   "Stinkbug",
//   "Stork",
//   "Swallow",
//   "Swan",
//   "Tapir",
//   "Tarsier",
//   "Termite",
//   "Tiger",
//   "Toad",
//   "Trout",
//   "Turkey",
//   "Turtle",
//   "Viper",
//   "Vulture",
//   "Wallaby",
//   "Walrus",
//   "Wasp",
//   "Weasel",
//   "Whale",
//   "Wildcat",
//   "Wolf",
//   "Wolverine",
//   "Wombat",
//   "Woodcock",
//   "Woodpecker",
//   "Worm",
//   "Wren",
//   "Yak",
//   "Zebra",
// ];

// //Q: อยากให้ปริ้นย้อนกลับไป

// for (let i = animals.length; i >= 0; i--) {
//   console.log(i, animals[i]);
// }

// let str = "LOL";

// for (let i = 0; i <= 5; i++) {
//   console.log("outer:", i);
//   for (let j = 0; j < str.length; j++) {
//     console.log("inner:", str[j]);
//   }
// }

let listOfAnimal = [
  ["Ant", "Bull", "Cat"],
  ["Dog", "Elephant", "Fly"],
  ["Giraff", "Hen", "Iel"],
];

// show list of each animal

for (let i = 0; i < listOfAnimal.length; i++) {
  console.log(listOfAnimal[i]);
  for (let j = 0; j < listOfAnimal[i].length; j++) {
    console.log(listOfAnimal[i][j]);
  }
}
